import React, { Component } from 'react';
import PropTypes from 'prop-types';


class ProvingProofOfWinner extends Component {
    constructor (props) {
        super(props);
        this.state = {
            hasError: false,
            showSending: false,
            proofOfWinner: '',
        }
        this.handleProvingProofOfWinner = this.handleProvingProofOfWinner.bind(this);
        this.handleProvingProofOfWinnerChange = this.handleProvingProofOfWinnerChange.bind(this);
        }

    handleProvingProofOfWinnerChange (field){
        return (event) => {
            this.setState({
                [field]: event.target.value
            })
        }
    }


    validation(app){
        if(app.proofOfWinner.length > 0){
            return true;
        } else {
            return false;
        }
    }

    handleProvingProofOfWinner(e){
        e.preventDefault();
        const { onClose, passInfo } = this.props;
        const web3 = this.props.web3;
        const parsedAbi = JSON.parse(this.props.contractAbi);
        const auctionContract = new web3.eth.Contract(parsedAbi, this.props.contractAddress);
        console.log(this.state.proofOfWinner);
        const parsedProofOfWinner = JSON.parse(this.state.proofOfWinner); 
        
        if(this.validation(this.state)){
            this.setState({showSending:true});
            (async () => {
                const accounts = await web3.eth.getAccounts();
                await auctionContract.methods.auctionEnd(parsedProofOfWinner.proof.a, parsedProofOfWinner.proof.b, parsedProofOfWinner.proof.c, parsedProofOfWinner.inputs).send({from: accounts[0], gas:3000000});
                const winner = await auctionContract.methods.getWinner().call();
                const biggest = await auctionContract.methods.getBiggestBid().call();
                console.log("el winner: " + winner);
                console.log("el biggest: " + biggest);
                passInfo(winner, biggest);
              })().then(onClose(true));
        }else{
            this.setState({
                hasError:true
            })
        }
    }


    render() {
        const { showSending, proofOfWinner, hasError} = this.state;
        const {onClose} = this.props;
        return (<div className="modal">
            <div className="modal-content">
                <span className="close" onClick={onClose(false)}>&times;</span>
                <h2>Placing a bid</h2>
                { showSending && (<span className="success"> Enviando... </span>)}
                { hasError && (<div className="error"> Some fields are empty or contain an wrong values. </div>)}
                <form>
                    <label>Proof generated by ZoKrates</label>
                    <input type="text" value={proofOfWinner} onChange={this.handleProvingProofOfWinnerChange("proofOfWinner")} minLength="3" maxLength="2000" required/>
                    <input type="submit" onClick={this.handleProvingProofOfWinner} value="Submit" disabled={showSending}/>
                </form>
            </div>
        </div>);
    }
}

ProvingProofOfWinner.propTypes = {
    onClose: PropTypes.func.isRequired,
    passInfo: PropTypes.func.isRequired,
    web3: PropTypes.object.isRequired,
    contractAddress: PropTypes.string.isRequired,
    contractAbi: PropTypes.string.isRequired
};

export default ProvingProofOfWinner;