import React, { Component } from 'react';
import PropTypes from 'prop-types';

class ProvingProofOfWinner extends Component {
    constructor (props) {
        super(props);
        this.state = {
            hasError: false,
            showSending: false,
            proofOfWinner: '',
        }
        this.handleProvingProofOfWinner = this.handleProvingProofOfWinner.bind(this);
        this.handleProvingProofOfWinnerChange = this.handleProvingProofOfWinnerChange.bind(this);
        }

    handleProvingProofOfWinnerChange (field){
        return (event) => {
            this.setState({
                [field]: event.target.value
            })
        }
    }


    validation(app){
        if(app.proofOfWinner.length > 0){
            return true;
        } else {
            return false;
        }
    }

    handleProvingProofOfWinner(e){
        e.preventDefault();
        const { onClose } = this.props;
        const web3 = this.props.web3;
        const parsedAbi = JSON.parse(this.props.contractAbi);
        const auctionContract = new web3.eth.Contract(parsedAbi, this.props.contractAddress);
        console.log(this.state.proofOfWinner);
        const parsedProofOfWinner = JSON.parse(this.state.proofOfWinner); 
        //const contract = web3.eth.contract(this.props.contractAbi);
        //const contractInstance = contract.at(this.props.contractAddress);
        if(this.validation(this.state)){
            this.setState({showSending:true});
            (async () => {
                console.log("Justo antes de bid prover");
                console.log(parsedProofOfWinner.proof.a);
                console.log(parsedProofOfWinner.proof.b);
                console.log(parsedProofOfWinner.proof.c);
                console.log(parsedProofOfWinner.proof.inputs);
                const accounts = await web3.eth.getAccounts();
                auctionContract.events.resultWinnerAndPosition((error, event) => {
                    if(!error){
                        console.log("winner amount is: " + event.winnerEvent + "position is: " + event.positionEvent);
                    }else{
                        console.log(error);
                    }
                });
                auctionContract.methods.auctionEnd(parsedProofOfWinner.proof.a, parsedProofOfWinner.proof.b, parsedProofOfWinner.proof.c, parsedProofOfWinner.inputs).send({from: accounts[0], gas:3000000}, function(error, result){
                    if(!error){
                        alert("You have proved your transaction successfully and you participate in the bid " + result);
                        //console.log(auctionContract.methods.getHashesZokrates(0).call());
                    }else{
                        alert("You have not proved your transaction successfully and you do not participate in the bid because of the following error: " + error);
                    }
                });
              })().then(onClose(true));
            
            //auctionContract.methods.bid(web3.utils.keccak256(web3.eth.abi.encodeParameters(['string', 'string', 'string'],[this.state.encryptedBid, this.state.hashZokrates1, this.state.hashZokrates2]))).send({from: accounts[0],to: this.props.contractAddress, value: 5}).then((f) => console.log(f))
            //contractInstance.bid.call()
            /*addVideo({
                title:this.state.title,
                description: this.state.description,
                url: this.state.url,
                thumbnail: `https://img.youtube.com/vi/${token}/maxresdefault.jpg`,
                embed: `https://www.youtube.com/embed/${token}`
            }).then(onClose(true));*/

        }else{
            this.setState({
                hasError:true
            })
        }
    }


    render() {
        const { showSending, proofOfWinner, hasError} = this.state;
        const {onClose} = this.props;
        return (<div className="modal">
            <div className="modal-content">
                <span className="close" onClick={onClose(false)}>&times;</span>
                <h2>Placing a bid</h2>
                { showSending && (<span className="success"> Enviando... </span>)}
                { hasError && (<div className="error"> Some fields are empty or contain an wrong values. </div>)}
                <form>
                    <label>Proof generated by ZoKrates</label>
                    <input type="text" value={proofOfWinner} onChange={this.handleProvingProofOfWinnerChange("proofOfWinner")} minLength="3" maxLength="2000" required/>
                    <input type="submit" onClick={this.handleProvingProofOfWinner} value="Submit" disabled={showSending}/>
                </form>
            </div>
        </div>);
    }
}

ProvingProofOfWinner.propTypes = {
    onClose: PropTypes.func.isRequired,
    web3: PropTypes.object.isRequired,
    contractAddress: PropTypes.string.isRequired,
    contractAbi: PropTypes.string.isRequired
};

export default ProvingProofOfWinner;